CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    senha_hash VARCHAR(100) NOT NULL,
    perfil VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_perfil CHECK (perfil IN ('SOLICITANTE', 'ATENDENTE', 'ADMIN')),
    CONSTRAINT ck_usuarios_nome_nao_vazio CHECK (TRIM(nome) <> ''),
    CONSTRAINT ck_usuarios_email_nao_vazio CHECK (TRIM(email) <> '')
);

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    versao BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_categorias_nome UNIQUE (nome),
    CONSTRAINT ck_categorias_nome_nao_vazio CHECK (TRIM(nome) <> '')
);

CREATE TABLE chamados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocolo VARCHAR(30) NOT NULL,
    titulo VARCHAR(160) NOT NULL,
    descricao TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ABERTO',
    prioridade VARCHAR(10) NOT NULL DEFAULT 'MEDIA',
    solicitante_id BIGINT NOT NULL,
    atendente_id BIGINT,
    categoria_id BIGINT NOT NULL,
    solucao TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolvido_em TIMESTAMP WITH TIME ZONE,
    fechado_em TIMESTAMP WITH TIME ZONE,
    versao BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_chamados_protocolo UNIQUE (protocolo),
    CONSTRAINT fk_chamados_solicitante FOREIGN KEY (solicitante_id) REFERENCES usuarios (id),
    CONSTRAINT fk_chamados_atendente FOREIGN KEY (atendente_id) REFERENCES usuarios (id),
    CONSTRAINT fk_chamados_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT ck_chamados_status CHECK (status IN ('ABERTO', 'EM_ATENDIMENTO', 'RESOLVIDO', 'FECHADO')),
    CONSTRAINT ck_chamados_prioridade CHECK (prioridade IN ('BAIXA', 'MEDIA', 'ALTA')),
    CONSTRAINT ck_chamados_titulo_nao_vazio CHECK (TRIM(titulo) <> ''),
    CONSTRAINT ck_chamados_descricao_nao_vazia CHECK (TRIM(descricao) <> ''),
    CONSTRAINT ck_chamados_resolvido_em CHECK (status NOT IN ('RESOLVIDO', 'FECHADO') OR resolvido_em IS NOT NULL),
    CONSTRAINT ck_chamados_fechado_em CHECK (status <> 'FECHADO' OR fechado_em IS NOT NULL)
);

CREATE TABLE comentarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chamado_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    conteudo TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comentarios_chamado FOREIGN KEY (chamado_id) REFERENCES chamados (id),
    CONSTRAINT fk_comentarios_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id),
    CONSTRAINT ck_comentarios_conteudo_nao_vazio CHECK (TRIM(conteudo) <> '')
);

CREATE TABLE historico_chamados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chamado_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    tipo_evento VARCHAR(20) NOT NULL,
    status_anterior VARCHAR(20),
    status_novo VARCHAR(20),
    prioridade_anterior VARCHAR(10),
    prioridade_nova VARCHAR(10),
    atendente_anterior_id BIGINT,
    atendente_novo_id BIGINT,
    justificativa VARCHAR(500),
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_historico_chamado FOREIGN KEY (chamado_id) REFERENCES chamados (id),
    CONSTRAINT fk_historico_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id),
    CONSTRAINT fk_historico_atendente_anterior FOREIGN KEY (atendente_anterior_id) REFERENCES usuarios (id),
    CONSTRAINT fk_historico_atendente_novo FOREIGN KEY (atendente_novo_id) REFERENCES usuarios (id),
    CONSTRAINT ck_historico_tipo_evento CHECK (tipo_evento IN ('CRIACAO', 'ATRIBUICAO', 'STATUS', 'PRIORIDADE')),
    CONSTRAINT ck_historico_status_anterior CHECK (status_anterior IS NULL OR status_anterior IN ('ABERTO', 'EM_ATENDIMENTO', 'RESOLVIDO', 'FECHADO')),
    CONSTRAINT ck_historico_status_novo CHECK (status_novo IS NULL OR status_novo IN ('ABERTO', 'EM_ATENDIMENTO', 'RESOLVIDO', 'FECHADO')),
    CONSTRAINT ck_historico_prioridade_anterior CHECK (prioridade_anterior IS NULL OR prioridade_anterior IN ('BAIXA', 'MEDIA', 'ALTA')),
    CONSTRAINT ck_historico_prioridade_nova CHECK (prioridade_nova IS NULL OR prioridade_nova IN ('BAIXA', 'MEDIA', 'ALTA'))
);

CREATE INDEX idx_chamados_solicitante_criado_em ON chamados (solicitante_id, criado_em);
CREATE INDEX idx_chamados_atendente_status ON chamados (atendente_id, status);
CREATE INDEX idx_chamados_status_prioridade_criado_em ON chamados (status, prioridade, criado_em);
CREATE INDEX idx_chamados_categoria_status ON chamados (categoria_id, status);
CREATE INDEX idx_comentarios_chamado_criado_em ON comentarios (chamado_id, criado_em);
CREATE INDEX idx_historico_chamado_criado_em ON historico_chamados (chamado_id, criado_em);
